### ISSUE TITLE
Addons 1.22 TODO

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/scratch-gui#352]
- [x] Finish migrating patches to https://github.com/TurboWarp/addons
 - [x] Use the new repository
 - [x] Make sure all patches were transferred properly
 - [x] Start using renamed properties
 - [x] Remove full version indicator
 - [x] editor-extra-keys: support dynamic settings change
 - [x] ~~hide-delete-button, fullscreen, tw-interface-customization: implement updateUserstylesOnSettingsChange~~ not important, can happen later
 - [x] swap-local-global, also update hardcoded context menu order
   - [x] pending upstream PR
 - [x] columns?
   - [x] dark mode
 - [x] editor comment previews?
   - [x] pending upstream PR
 - [x] ~~enhanced fullscreen~~ maybe next time
