### ISSUE TITLE
Addons 1.23 TODO

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/scratch-gui#373]
- [x] Upstream broke apart project-info and now has a block-count addon, basically doing what we already did with tw-project-info. So let's start using upstream's version instead. Might include the first addon storage migration.
- [x] Break apart tw-interface-customization. Will require storage migration.
- [x] For non-conditional userscripts, we should use `import` instead of `require`
